# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "MATH 4/5388: Machine Learning Methods"
author: Farhad Pourkamali
copyright: "2026, Farhad Pourkamali"
logo: logo.png
only_build_toc_files: true

# Do NOT execute notebooks on CI
execute:
  execute_notebooks: "off"     # options: "off", "auto", "force", "cache"
  allow_errors: false
  exclude_patterns: []          # you can add files here later to skip specific ones

repository:
  url: https://github.com/farhad-pourkamali/MLMethods
  branch: main
  path_to_book: .

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true



